// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qesagurxtdvgwmlzajmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlc2FndXJ4dGR2Z3dtbHpham1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTMxMjMsImV4cCI6MjA1ODg4OTEyM30.O570I6PDgVcO53XEWDdOFEwjM8A-cngu-ep5p4IcByU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);