// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = 'https://brquajnyriybaruurgzu.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycXVham55cml5YmFydXVyZ3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjQ3NjQsImV4cCI6MjA1NzM0MDc2NH0.4TvZpf2EaThErlDy1_7ZBIlsE7S-kNoq1iJt7EHCPDU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);